//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure_and_Maintaince_and_monitoring_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Asset_Transfer
    {
        public int ATid { get; set; }
        public System.DateTime TransferDate { get; set; }
        public int From_RoomID { get; set; }
        public int To_RoomID { get; set; }
        public int AssetID { get; set; }
        public short Quantity { get; set; }
    
        public virtual Tbl_Asset Tbl_Asset { get; set; }
        public virtual Tbl_Room Tbl_Room { get; set; }
        public virtual Tbl_Room Tbl_Room1 { get; set; }
    }
}
