//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure_and_Maintaince_and_monitoring_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Complain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Complain()
        {
            this.Tbl_Complaint_User = new HashSet<Tbl_Complaint_User>();
            this.Tbl_Feedback = new HashSet<Tbl_Feedback>();
        }
    
        public int ComplainID { get; set; }
        public string Description { get; set; }
        public int ComplaintType { get; set; }
        public int ClassID { get; set; }
        public string Image { get; set; }
        public string Status { get; set; }
    
        public virtual Tbl_ComplaintType Tbl_ComplaintType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Complaint_User> Tbl_Complaint_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Feedback> Tbl_Feedback { get; set; }
    }
}
